# Generated by Django 6.0.6 on 2026-06-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Store',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='store',
        ),
    ]
