# Generated by Django 6.0.6 on 2026-07-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productreviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='content',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='productreviews',
            name='stars',
        ),
        migrations.AddField(
            model_name='productreviews',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None),
        ),
    ]
