# Generated by Django 6.0.6 on 2026-07-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_profile_user_type_order_vendors_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
