# Generated by Django 6.0.6 on 2026-07-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vendor',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('Vendor', 'Vendor'), ('Customer', 'Customer')], default='Customer', max_length=10),
        ),
    ]
