# Generated by Django 6.0.6 on 2026-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_profile_vendor_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='uploads/product/'),
        ),
    ]
