# Generated by Django 6.0.6 on 2026-07-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_order_address_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
