# Generated by Django 6.0.6 on 2026-07-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productreviews_verified_alter_productreviews_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='verified',
            new_name='bought',
        ),
    ]
